### ISSUE TITLE
Partner list

### ISSUE THREAD

**Issue by jenkack** [labopm/website#16]
Don't include university and non-profit partners at launch, vet them in future, as we will need those parties to sign off on the use of their name. No agency seals on our materials.

**Comment by humancompanion** [comment]
Are we talking about this page: https://federalist-proxy.app.cloud.gov/site/labopm/website/what-we-do/partner/ ?

If so, it's in Markdown. Edit away! (Just let me know if/when you do please)

**Comment by jenkack** [comment]
That's the one! I have never done updates in github... can we do a quick tutorial this week on how I do this without screwing anything up? Or are there steps you can note in here? I read through this but still could use guidance:

https://help.github.com/en/articles/about-pull-requests

**Comment by humancompanion** [comment]
We can do a quick Zoom chat to go through it. It's pretty simple though. I created a branch for content updates:

https://github.com/labopm/website/tree/content-updates

1. Navigate to that link, then find the file you want to change (it will be under pages/).
2. Click the edit icon (pencil), next to the trash icon, in order to edit the file.
3. Make changes (this one in particular does have some HTML on that page. Sorry forgot that list was side-by-side).
4. Add a commit note at the bottom and commit your changes. They'll just be committed to the branch. You can preview those changes on Federalist (once we make the initial commit to this branch, I'll provide you with the URL).
5. Then go to new Pull Request: https://github.com/labopm/website/compare
6. Click on the branch name (content-updates) and github should take it from there. Just fill out the form and submit the pull request.
7. I take a look at it and if it looks good, I merge it in. Once I do, Fedearlist rebuilds the site and out the change goes!

**Comment by jenkack** [comment]
Thanks, these instructions are clear, I'll give it a shot without the zoom tutorial, will let you know if I run into any trouble.
