### ISSUE TITLE
Questions for Matt

### ISSUE THREAD

**Issue by jenkack** [labopm/website#21]
Starting a list of things Jen/the Lab should know how to do before Matt leaves:

- Prep/add/change photos
- Add/remove pages (add Aaron to people)
- Add/remove navs
- Pushing changes live (unless we get this info from federalist)
- Where to update class dates
- Where to update footer
- Can you do site-wide text searches?

6/18/19
- Uploading photos
- What we do > overview, first graph style
- Should we change page filenames if changing titles/navs?
- Adjusting addresses in footer and locations page
- Pushing changes/merging: isn't "my" branch and content-updates the same?

ADDING A PEOPLE PHOTO

Naming your image
When you upload a person image to github please name it in the following format:

[first-last].[MIME type]
For example:

sean-baker.jpg
Connecting your image to your page
When you are done you need to add that same image filename to the front-matter of your person page using the key "image_name:". For example:

image_name: sean-baker.jpg

**Comment by humancompanion** [comment]
I know we are meeting to discuss but, I figured I'd answer here in print so you can refer back to the answers:

* Photos: Tim has been doing the prep. I just added the REAME I had put in the people images directory (where it was unlikely to be seen) into the main repo README content.
* Adding pages: What I would recommend for those adding pages via github is to navigation to a page they want to duplicate (just as a draft), edit that file, copy the contents, then use the "Create new file" button (it's in the top right when you are viewing a directory) and paste the content in, then modify as needed. Just be sure to stress that one must change the permalink or it could overwrite the other file when building. (In other words, two pages with the same permalink will result in only one winner)
* Add/removing navigation should just be a matter of editing _data/navigation.yml and commenting our what you don't want and adding what you do want. The formatting is persnickety (spaces only, no tabs), but otherwise it is quite simple.
* Pushing changes. Follow the pull request process I outlined via Slack. I'm fairly certain you can find that workflow documented on the web as well. We didn't invent the idea.
* Class dates are stored in the front-matter YML for each class. The keys are:
    * next-offering
    * next-offering-location
Pretty much everything in Jekyll is done via front-matter. The Jekyll docs are useful: https://jekyllrb.com/docs/ as is this Cheatsheet: https://devhints.io/jekyll
* The footer is in _includes/_footer.html
* You can do a site wide text search if you clone the repo to your Mac and then use the search in Finder? I don't know, I use command line tools like ack to search. GitHub does not appear to have site-wide search.

**Comment by jenkack** [comment]
@humancompanion Thanks, this is super helpful, will tackle a bunch of things today so if I run into trouble we can address tomorrow when we meet.
